# Generated by Django 4.2.4 on 2023-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Blog Image')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Image')),
                ('content', models.TextField(max_length=255, verbose_name='Blog Image')),
                ('date', models.DateTimeField(verbose_name='Blog Image')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
            },
        ),
    ]
