# Generated by Django 4.2.4 on 2023-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="introduction",
            name="content",
            field=models.TextField(max_length=255, verbose_name="Blog Content"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="date",
            field=models.DateTimeField(verbose_name="Blog Date"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Blog Title"),
        ),
    ]
