# Generated by Django 4.2.4 on 2023-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=255, verbose_name="Icon")),
                ("text", models.TextField(verbose_name="Icon Text")),
            ],
            options={
                "verbose_name": "Icon",
                "verbose_name_plural": "Icons",
            },
        ),
    ]
