# Generated by Django 4.2.4 on 2023-08-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="media", verbose_name="Image: ")),
                ("title", models.CharField(max_length=255, verbose_name="Title: ")),
                ("subtitle", models.CharField(max_length=255, verbose_name="Title: ")),
            ],
            options={
                "verbose_name": "Our Gallery",
                "verbose_name_plural": "Our Galleries",
            },
        ),
    ]
