# Generated by Django 4.2.4 on 2023-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="content3",
            field=models.TextField(default=1, verbose_name="Third Content"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="content2",
            field=models.TextField(verbose_name="Second Content"),
        ),
    ]
