# Generated by Django 4.2.4 on 2023-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_aboutus_content3_alter_aboutus_content2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text ")),
                ("name", models.CharField(max_length=255, verbose_name="User Name")),
                ("email", models.EmailField(max_length=254, verbose_name="User Email")),
                ("message", models.TextField(verbose_name="User Text")),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
    ]
