# Generated by Django 4.2.4 on 2023-08-04 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_contactus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="text",
        ),
    ]
