# Generated by Django 4.2.4 on 2023-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_contactus_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bg1", models.ImageField(upload_to="media", verbose_name="Image 1")),
                ("bg2", models.ImageField(upload_to="media", verbose_name="Image 2")),
                ("bg3", models.ImageField(upload_to="media", verbose_name="Image 3")),
                ("bg4", models.ImageField(upload_to="media", verbose_name="Image 4")),
            ],
            options={
                "verbose_name": "Home BackGround",
                "verbose_name_plural": "Home BackGround",
            },
        ),
    ]
